### ISSUE TITLE
Feature request: support for orderby_sort on store fields

### ISSUE THREAD

**Issue by peteheaney** [low/low_search_store#1]
While it's possible to order/sort results with an *orderby* field and a *sort* field, it doesn't seem to be possible to use the *orderby_sort* shortcut. Is this a feature that can be added?

Thanks

**Comment by low** [comment]
This should be possible already. LS sets the `orderby` and `sort` params based on the `orderby_sort` parameter. What code are you using?

**Comment by peteheaney** [comment]
Using two separate fields like this works as expected:

    <select class="form-control" name="orderby" id="orderby">
		<option value=""></option>
		<option value="store:price"{if low_search_orderby == 'store:price'} selected{/if}>
			Price
		</option>
	</select>
	<select class="form-control" name="sort" id="sort">
		<option value=""></option>
			<option value="asc"{if low_search_sort == 'asc'} selected{/if}>ascending</option>
			<option value="desc"{if low_search_sort == 'desc'} selected{/if}>descending</option>
	</select>

But using one orderby_sort field has no effect on the order/sort of results:

    <select class="form-control" name="orderby_sort" id="orderby_sort">
		<option value=""></option>
		<option value="store:price|sort:asc"{if low_search_orderby_sort == 'store:price|sort:asc'} selected{/if}>
			Price (Low to High)
		</option>
		<option value="store:price|sort:desc"{if low_search_orderby_sort == 'store:price|sort:desc'} selected{/if}>
			Price (High to Low)
		</option>
	</select>

**Comment by low** [comment]
Try removing the `sort:` prefix there. So `value="store:price|asc"`.

**Comment by peteheaney** [comment]
No I'm afraid that didn't make a difference.

A bit more detail: it displays the results in ascending order, regardless of whether the sort is *asc* or *desc*.  Not sure if that helps with diagnosis.

**Comment by low** [comment]
Try and download Low Search Store again. I made a small change to fix the sorting bug.

**Comment by peteheaney** [comment]
Aha, that worked! Thanks!
