### ISSUE TITLE
Feature request: ability to filter by 'on sale'

### ISSUE THREAD

**Issue by peteheaney** [low/low_search_store#2]
Hi Low, would it be possible to add the ability to filter store entries by whether or not the product is 'on sale'?  Basically, the same as you can do with [Store's native search tag](https://www.exp-resso.com/docs/search_tag.html).

Thanks

**Comment by low** [comment]
I've looked at how Store does this, but it seems Store doesn't use its own data to determine whether or not a product is on sale. What products would you consider to be "on sale"?

**Comment by peteheaney** [comment]
'Sales' are stored in a separate db table (exp_store_sales).  You basically setup a sale in the Store settings in the CP and then restrict that sale to one or more entries, categories and/or member groups.

So for example, if I create a sale and restrict it to all entries in the category 'Samsung', it will add a row to the exp_store_sales table with the category_ids column populated with the ID of the Samsung category.

Also bear in mind that an entry must meet all of the restrictions to appear as 'on sale'.  So if I've restricted the sale to a category and a member group, it has to meet both of those criteria in order to appear 'on sale'.

So to filter search results by 'on sale', I think you'd essentially need to only show entries that:

1. appear in the 'entry_ids' column in any row in the exp_store_sales table, and
2. belong to one of the categories that appear in the 'category_ids' column in any row the exp_store_sales table

You'd also need to check the member group of the user against the member_group_ids column.

Here's an example of what the exp_store_sales table looks like with a couple of sales configured:

![exp_store_sales](https://cloud.githubusercontent.com/assets/234166/6389184/bb61aa00-bd99-11e4-9b18-a41f0425ef18.png)

**Comment by low** [comment]
Thanks, that clarifies things. I'll look into it.

**Comment by low** [comment]
There, give it a try.

**Comment by peteheaney** [comment]
Thanks. What do I have to set on_sale to in order to only see sale items?  I've tried 'yes', 'true' and '1' but none of them worked.

**Comment by peteheaney** [comment]
Further to that, if I set the results tag parameter default:store:on_sale="yes", it returns no results.  If I set that parameter to "true" or "1", it has no effect on the results (returns everything).  So I'm guessing "yes" is the right word, but it's not working for some reason.

**Comment by low** [comment]
Should be `store:on_sale="yes"`. Guess I should have a better set of data to test with... I'll look into it.

**Comment by low** [comment]
How 'bout now?

**Comment by peteheaney** [comment]
Yes, that seems to be working perfectly now.  Excellent, thanks!
